#pragma once

#include "sootDefs.h"
#include "state.h"

#include "nucleationModels/nucleationModel.h"
#include "nucleationModels/nucleationModel_LL.h"
#include "nucleationModels/nucleationModel_LIN.h"
#include "nucleationModels/nucleationModel_LINA1.h"
#include "nucleationModels/nucleationModel_PAH.h"
#include "nucleationModels/nucleationModel_MB.h"
#include "nucleationModels/nucleationModel_FAIR.h"
#include "nucleationModels/nucleationModel_AJ_RED.h"
#include "nucleationModels/nucleationModel_NONE.h"

#include "growthModels/growthModel.h"
#include "growthModels/growthModel_LL.h"
#include "growthModels/growthModel_LIN.h"
#include "growthModels/growthModel_HACA.h"
#include "growthModels/growthModel_MB.h"
#include "growthModels/growthModel_FAIR.h"
#include "growthModels/growthModel_NONE.h"

#include "oxidationModels/oxidationModel.h"
#include "oxidationModels/oxidationModel_LL.h"
#include "oxidationModels/oxidationModel_LEE_NEOH.h"
#include "oxidationModels/oxidationModel_NSC_NEOH.h"
#include "oxidationModels/oxidationModel_HACA.h"
#include "oxidationModels/oxidationModel_OPTJ.h"
#include "oxidationModels/oxidationModel_OPTG.h"
#include "oxidationModels/oxidationModel_MB.h"
#include "oxidationModels/oxidationModel_FAIR.h"
#include "oxidationModels/oxidationModel_AJ_RED.h"
#include "oxidationModels/oxidationModel_NONE.h"

#include "coagulationModels/coagulationModel.h"
#include "coagulationModels/coagulationModel_CONTINUUM.h"
#include "coagulationModels/coagulationModel_FM.h"
#include "coagulationModels/coagulationModel_HM.h"
#include "coagulationModels/coagulationModel_FUCHS.h"
#include "coagulationModels/coagulationModel_NONE.h"

#include "tarModels/tarModel.h"
#include "tarModels/tarModel_NONE.h"
#include "tarModels/tarModel_AJ_RED.h"

#include "sootModel_MONO.h"
#include "sootModel_LOGN.h"
#include "sootModel_QMOM.h"
#include "sootModel_MOMIC.h"
#include "sootModel_SECT.h"
